/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppHomepageRouteImport } from './routes/_app/homepage'
import { Route as AppDealsRouteImport } from './routes/_app/deals'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppDealsIndexRouteImport } from './routes/_app/deals/index'
import { Route as AppAuditIndexRouteImport } from './routes/_app/audit/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppDealsNewRouteImport } from './routes/_app/deals/new'
import { Route as AppAuditTraceIdRouteImport } from './routes/_app/audit/$traceId'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminRolesRouteImport } from './routes/_app/admin/roles'
import { Route as AppAdminGroupsRouteImport } from './routes/_app/admin/groups'
import { Route as AppAuditTraceIdIndexRouteImport } from './routes/_app/audit/$traceId.index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users.index'
import { Route as AppAdminRolesIndexRouteImport } from './routes/_app/admin/roles.index'
import { Route as AppAdminGroupsIndexRouteImport } from './routes/_app/admin/groups.index'
import { Route as AppAuditTraceIdVisualizerRouteImport } from './routes/_app/audit/$traceId.visualizer'
import { Route as AppAdminRolesRoleIdRouteImport } from './routes/_app/admin/roles.$roleId'
import { Route as AppAdminGroupsGroupIdRouteImport } from './routes/_app/admin/groups.$groupId'
import { Route as AppAdminUsersUserIdAssignRouteImport } from './routes/_app/admin/users.$userId.assign'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomepageRoute = AppHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsRoute = AppDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsIndexRoute = AppDealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDealsRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDealsNewRoute = AppDealsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDealsRoute,
} as any)
const AppAuditTraceIdRoute = AppAuditTraceIdRouteImport.update({
  id: '/$traceId',
  path: '/$traceId',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminGroupsRoute = AppAdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAuditTraceIdIndexRoute = AppAuditTraceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuditTraceIdRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminUsersRoute,
} as any)
const AppAdminRolesIndexRoute = AppAdminRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRolesRoute,
} as any)
const AppAdminGroupsIndexRoute = AppAdminGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminGroupsRoute,
} as any)
const AppAuditTraceIdVisualizerRoute =
  AppAuditTraceIdVisualizerRouteImport.update({
    id: '/visualizer',
    path: '/visualizer',
    getParentRoute: () => AppAuditTraceIdRoute,
  } as any)
const AppAdminRolesRoleIdRoute = AppAdminRolesRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => AppAdminRolesRoute,
} as any)
const AppAdminGroupsGroupIdRoute = AppAdminGroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => AppAdminGroupsRoute,
} as any)
const AppAdminUsersUserIdAssignRoute =
  AppAdminUsersUserIdAssignRouteImport.update({
    id: '/$userId/assign',
    path: '/$userId/assign',
    getParentRoute: () => AppAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/audit': typeof AppAuditRouteWithChildren
  '/deals': typeof AppDealsRouteWithChildren
  '/homepage': typeof AppHomepageRoute
  '/admin/groups': typeof AppAdminGroupsRouteWithChildren
  '/admin/roles': typeof AppAdminRolesRouteWithChildren
  '/admin/users': typeof AppAdminUsersRouteWithChildren
  '/audit/$traceId': typeof AppAuditTraceIdRouteWithChildren
  '/deals/new': typeof AppDealsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AppAdminIndexRoute
  '/audit/': typeof AppAuditIndexRoute
  '/deals/': typeof AppDealsIndexRoute
  '/admin/groups/$groupId': typeof AppAdminGroupsGroupIdRoute
  '/admin/roles/$roleId': typeof AppAdminRolesRoleIdRoute
  '/audit/$traceId/visualizer': typeof AppAuditTraceIdVisualizerRoute
  '/admin/groups/': typeof AppAdminGroupsIndexRoute
  '/admin/roles/': typeof AppAdminRolesIndexRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/audit/$traceId/': typeof AppAuditTraceIdIndexRoute
  '/admin/users/$userId/assign': typeof AppAdminUsersUserIdAssignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/homepage': typeof AppHomepageRoute
  '/deals/new': typeof AppDealsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AppAdminIndexRoute
  '/audit': typeof AppAuditIndexRoute
  '/deals': typeof AppDealsIndexRoute
  '/admin/groups/$groupId': typeof AppAdminGroupsGroupIdRoute
  '/admin/roles/$roleId': typeof AppAdminRolesRoleIdRoute
  '/audit/$traceId/visualizer': typeof AppAuditTraceIdVisualizerRoute
  '/admin/groups': typeof AppAdminGroupsIndexRoute
  '/admin/roles': typeof AppAdminRolesIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/audit/$traceId': typeof AppAuditTraceIdIndexRoute
  '/admin/users/$userId/assign': typeof AppAdminUsersUserIdAssignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/audit': typeof AppAuditRouteWithChildren
  '/_app/deals': typeof AppDealsRouteWithChildren
  '/_app/homepage': typeof AppHomepageRoute
  '/_app/admin/groups': typeof AppAdminGroupsRouteWithChildren
  '/_app/admin/roles': typeof AppAdminRolesRouteWithChildren
  '/_app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/_app/audit/$traceId': typeof AppAuditTraceIdRouteWithChildren
  '/_app/deals/new': typeof AppDealsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/audit/': typeof AppAuditIndexRoute
  '/_app/deals/': typeof AppDealsIndexRoute
  '/_app/admin/groups/$groupId': typeof AppAdminGroupsGroupIdRoute
  '/_app/admin/roles/$roleId': typeof AppAdminRolesRoleIdRoute
  '/_app/audit/$traceId/visualizer': typeof AppAuditTraceIdVisualizerRoute
  '/_app/admin/groups/': typeof AppAdminGroupsIndexRoute
  '/_app/admin/roles/': typeof AppAdminRolesIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/audit/$traceId/': typeof AppAuditTraceIdIndexRoute
  '/_app/admin/users/$userId/assign': typeof AppAdminUsersUserIdAssignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/audit'
    | '/deals'
    | '/homepage'
    | '/admin/groups'
    | '/admin/roles'
    | '/admin/users'
    | '/audit/$traceId'
    | '/deals/new'
    | '/api/auth/$'
    | '/admin/'
    | '/audit/'
    | '/deals/'
    | '/admin/groups/$groupId'
    | '/admin/roles/$roleId'
    | '/audit/$traceId/visualizer'
    | '/admin/groups/'
    | '/admin/roles/'
    | '/admin/users/'
    | '/audit/$traceId/'
    | '/admin/users/$userId/assign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/homepage'
    | '/deals/new'
    | '/api/auth/$'
    | '/admin'
    | '/audit'
    | '/deals'
    | '/admin/groups/$groupId'
    | '/admin/roles/$roleId'
    | '/audit/$traceId/visualizer'
    | '/admin/groups'
    | '/admin/roles'
    | '/admin/users'
    | '/audit/$traceId'
    | '/admin/users/$userId/assign'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/audit'
    | '/_app/deals'
    | '/_app/homepage'
    | '/_app/admin/groups'
    | '/_app/admin/roles'
    | '/_app/admin/users'
    | '/_app/audit/$traceId'
    | '/_app/deals/new'
    | '/api/auth/$'
    | '/_app/admin/'
    | '/_app/audit/'
    | '/_app/deals/'
    | '/_app/admin/groups/$groupId'
    | '/_app/admin/roles/$roleId'
    | '/_app/audit/$traceId/visualizer'
    | '/_app/admin/groups/'
    | '/_app/admin/roles/'
    | '/_app/admin/users/'
    | '/_app/audit/$traceId/'
    | '/_app/admin/users/$userId/assign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/homepage': {
      id: '/_app/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof AppHomepageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals': {
      id: '/_app/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AppDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals/': {
      id: '/_app/deals/'
      path: '/'
      fullPath: '/deals/'
      preLoaderRoute: typeof AppDealsIndexRouteImport
      parentRoute: typeof AppDealsRoute
    }
    '/_app/audit/': {
      id: '/_app/audit/'
      path: '/'
      fullPath: '/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/deals/new': {
      id: '/_app/deals/new'
      path: '/new'
      fullPath: '/deals/new'
      preLoaderRoute: typeof AppDealsNewRouteImport
      parentRoute: typeof AppDealsRoute
    }
    '/_app/audit/$traceId': {
      id: '/_app/audit/$traceId'
      path: '/$traceId'
      fullPath: '/audit/$traceId'
      preLoaderRoute: typeof AppAuditTraceIdRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/groups': {
      id: '/_app/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AppAdminGroupsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/audit/$traceId/': {
      id: '/_app/audit/$traceId/'
      path: '/'
      fullPath: '/audit/$traceId/'
      preLoaderRoute: typeof AppAuditTraceIdIndexRouteImport
      parentRoute: typeof AppAuditTraceIdRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/_app/admin/roles/': {
      id: '/_app/admin/roles/'
      path: '/'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AppAdminRolesIndexRouteImport
      parentRoute: typeof AppAdminRolesRoute
    }
    '/_app/admin/groups/': {
      id: '/_app/admin/groups/'
      path: '/'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AppAdminGroupsIndexRouteImport
      parentRoute: typeof AppAdminGroupsRoute
    }
    '/_app/audit/$traceId/visualizer': {
      id: '/_app/audit/$traceId/visualizer'
      path: '/visualizer'
      fullPath: '/audit/$traceId/visualizer'
      preLoaderRoute: typeof AppAuditTraceIdVisualizerRouteImport
      parentRoute: typeof AppAuditTraceIdRoute
    }
    '/_app/admin/roles/$roleId': {
      id: '/_app/admin/roles/$roleId'
      path: '/$roleId'
      fullPath: '/admin/roles/$roleId'
      preLoaderRoute: typeof AppAdminRolesRoleIdRouteImport
      parentRoute: typeof AppAdminRolesRoute
    }
    '/_app/admin/groups/$groupId': {
      id: '/_app/admin/groups/$groupId'
      path: '/$groupId'
      fullPath: '/admin/groups/$groupId'
      preLoaderRoute: typeof AppAdminGroupsGroupIdRouteImport
      parentRoute: typeof AppAdminGroupsRoute
    }
    '/_app/admin/users/$userId/assign': {
      id: '/_app/admin/users/$userId/assign'
      path: '/$userId/assign'
      fullPath: '/admin/users/$userId/assign'
      preLoaderRoute: typeof AppAdminUsersUserIdAssignRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
  }
}

interface AppAdminGroupsRouteChildren {
  AppAdminGroupsGroupIdRoute: typeof AppAdminGroupsGroupIdRoute
  AppAdminGroupsIndexRoute: typeof AppAdminGroupsIndexRoute
}

const AppAdminGroupsRouteChildren: AppAdminGroupsRouteChildren = {
  AppAdminGroupsGroupIdRoute: AppAdminGroupsGroupIdRoute,
  AppAdminGroupsIndexRoute: AppAdminGroupsIndexRoute,
}

const AppAdminGroupsRouteWithChildren = AppAdminGroupsRoute._addFileChildren(
  AppAdminGroupsRouteChildren,
)

interface AppAdminRolesRouteChildren {
  AppAdminRolesRoleIdRoute: typeof AppAdminRolesRoleIdRoute
  AppAdminRolesIndexRoute: typeof AppAdminRolesIndexRoute
}

const AppAdminRolesRouteChildren: AppAdminRolesRouteChildren = {
  AppAdminRolesRoleIdRoute: AppAdminRolesRoleIdRoute,
  AppAdminRolesIndexRoute: AppAdminRolesIndexRoute,
}

const AppAdminRolesRouteWithChildren = AppAdminRolesRoute._addFileChildren(
  AppAdminRolesRouteChildren,
)

interface AppAdminUsersRouteChildren {
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
  AppAdminUsersUserIdAssignRoute: typeof AppAdminUsersUserIdAssignRoute
}

const AppAdminUsersRouteChildren: AppAdminUsersRouteChildren = {
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
  AppAdminUsersUserIdAssignRoute: AppAdminUsersUserIdAssignRoute,
}

const AppAdminUsersRouteWithChildren = AppAdminUsersRoute._addFileChildren(
  AppAdminUsersRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminGroupsRoute: typeof AppAdminGroupsRouteWithChildren
  AppAdminRolesRoute: typeof AppAdminRolesRouteWithChildren
  AppAdminUsersRoute: typeof AppAdminUsersRouteWithChildren
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminGroupsRoute: AppAdminGroupsRouteWithChildren,
  AppAdminRolesRoute: AppAdminRolesRouteWithChildren,
  AppAdminUsersRoute: AppAdminUsersRouteWithChildren,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppAuditTraceIdRouteChildren {
  AppAuditTraceIdVisualizerRoute: typeof AppAuditTraceIdVisualizerRoute
  AppAuditTraceIdIndexRoute: typeof AppAuditTraceIdIndexRoute
}

const AppAuditTraceIdRouteChildren: AppAuditTraceIdRouteChildren = {
  AppAuditTraceIdVisualizerRoute: AppAuditTraceIdVisualizerRoute,
  AppAuditTraceIdIndexRoute: AppAuditTraceIdIndexRoute,
}

const AppAuditTraceIdRouteWithChildren = AppAuditTraceIdRoute._addFileChildren(
  AppAuditTraceIdRouteChildren,
)

interface AppAuditRouteChildren {
  AppAuditTraceIdRoute: typeof AppAuditTraceIdRouteWithChildren
  AppAuditIndexRoute: typeof AppAuditIndexRoute
}

const AppAuditRouteChildren: AppAuditRouteChildren = {
  AppAuditTraceIdRoute: AppAuditTraceIdRouteWithChildren,
  AppAuditIndexRoute: AppAuditIndexRoute,
}

const AppAuditRouteWithChildren = AppAuditRoute._addFileChildren(
  AppAuditRouteChildren,
)

interface AppDealsRouteChildren {
  AppDealsNewRoute: typeof AppDealsNewRoute
  AppDealsIndexRoute: typeof AppDealsIndexRoute
}

const AppDealsRouteChildren: AppDealsRouteChildren = {
  AppDealsNewRoute: AppDealsNewRoute,
  AppDealsIndexRoute: AppDealsIndexRoute,
}

const AppDealsRouteWithChildren = AppDealsRoute._addFileChildren(
  AppDealsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAuditRoute: typeof AppAuditRouteWithChildren
  AppDealsRoute: typeof AppDealsRouteWithChildren
  AppHomepageRoute: typeof AppHomepageRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAuditRoute: AppAuditRouteWithChildren,
  AppDealsRoute: AppDealsRouteWithChildren,
  AppHomepageRoute: AppHomepageRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
