/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTimesheetRouteImport } from './routes/_app/timesheet'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppHomepageRouteImport } from './routes/_app/homepage'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppDealsRouteImport } from './routes/_app/deals'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppTimesheetIndexRouteImport } from './routes/_app/timesheet/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppExpensesIndexRouteImport } from './routes/_app/expenses/index'
import { Route as AppDealsIndexRouteImport } from './routes/_app/deals/index'
import { Route as AppAuditIndexRouteImport } from './routes/_app/audit/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppDealsNewRouteImport } from './routes/_app/deals/new'
import { Route as AppDealsDealIdRouteImport } from './routes/_app/deals/$dealId'
import { Route as AppAuditTraceIdRouteImport } from './routes/_app/audit/$traceId'
import { Route as AppApprovalsTimesheetsRouteImport } from './routes/_app/approvals/timesheets'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminRolesRouteImport } from './routes/_app/admin/roles'
import { Route as AppAdminGroupsRouteImport } from './routes/_app/admin/groups'
import { Route as AppAuditTraceIdIndexRouteImport } from './routes/_app/audit/$traceId.index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users.index'
import { Route as AppAdminRolesIndexRouteImport } from './routes/_app/admin/roles.index'
import { Route as AppAdminGroupsIndexRouteImport } from './routes/_app/admin/groups.index'
import { Route as AppDealsDealIdSignRouteImport } from './routes/_app/deals/$dealId/sign'
import { Route as AppDealsDealIdSendProposalRouteImport } from './routes/_app/deals/$dealId/send-proposal'
import { Route as AppDealsDealIdQualifyRouteImport } from './routes/_app/deals/$dealId/qualify'
import { Route as AppDealsDealIdProposalRouteImport } from './routes/_app/deals/$dealId/proposal'
import { Route as AppDealsDealIdNegotiateRouteImport } from './routes/_app/deals/$dealId/negotiate'
import { Route as AppDealsDealIdEstimateRouteImport } from './routes/_app/deals/$dealId/estimate'
import { Route as AppAuditTraceIdVisualizerRouteImport } from './routes/_app/audit/$traceId.visualizer'
import { Route as AppAdminRolesRoleIdRouteImport } from './routes/_app/admin/roles.$roleId'
import { Route as AppAdminGroupsGroupIdRouteImport } from './routes/_app/admin/groups.$groupId'
import { Route as AppProjectsProjectIdInvoicesNewRouteImport } from './routes/_app/projects/$projectId/invoices/new'
import { Route as AppAdminUsersUserIdAssignRouteImport } from './routes/_app/admin/users.$userId.assign'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimesheetRoute = AppTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppHomepageRoute = AppHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsRoute = AppDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppTimesheetIndexRoute = AppTimesheetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTimesheetRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppExpensesRoute,
} as any)
const AppDealsIndexRoute = AppDealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDealsRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppDealsNewRoute = AppDealsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDealsRoute,
} as any)
const AppDealsDealIdRoute = AppDealsDealIdRouteImport.update({
  id: '/$dealId',
  path: '/$dealId',
  getParentRoute: () => AppDealsRoute,
} as any)
const AppAuditTraceIdRoute = AppAuditTraceIdRouteImport.update({
  id: '/$traceId',
  path: '/$traceId',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppApprovalsTimesheetsRoute = AppApprovalsTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AppApprovalsRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminGroupsRoute = AppAdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAuditTraceIdIndexRoute = AppAuditTraceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuditTraceIdRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminUsersRoute,
} as any)
const AppAdminRolesIndexRoute = AppAdminRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRolesRoute,
} as any)
const AppAdminGroupsIndexRoute = AppAdminGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminGroupsRoute,
} as any)
const AppDealsDealIdSignRoute = AppDealsDealIdSignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => AppDealsDealIdRoute,
} as any)
const AppDealsDealIdSendProposalRoute =
  AppDealsDealIdSendProposalRouteImport.update({
    id: '/send-proposal',
    path: '/send-proposal',
    getParentRoute: () => AppDealsDealIdRoute,
  } as any)
const AppDealsDealIdQualifyRoute = AppDealsDealIdQualifyRouteImport.update({
  id: '/qualify',
  path: '/qualify',
  getParentRoute: () => AppDealsDealIdRoute,
} as any)
const AppDealsDealIdProposalRoute = AppDealsDealIdProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => AppDealsDealIdRoute,
} as any)
const AppDealsDealIdNegotiateRoute = AppDealsDealIdNegotiateRouteImport.update({
  id: '/negotiate',
  path: '/negotiate',
  getParentRoute: () => AppDealsDealIdRoute,
} as any)
const AppDealsDealIdEstimateRoute = AppDealsDealIdEstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => AppDealsDealIdRoute,
} as any)
const AppAuditTraceIdVisualizerRoute =
  AppAuditTraceIdVisualizerRouteImport.update({
    id: '/visualizer',
    path: '/visualizer',
    getParentRoute: () => AppAuditTraceIdRoute,
  } as any)
const AppAdminRolesRoleIdRoute = AppAdminRolesRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => AppAdminRolesRoute,
} as any)
const AppAdminGroupsGroupIdRoute = AppAdminGroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => AppAdminGroupsRoute,
} as any)
const AppProjectsProjectIdInvoicesNewRoute =
  AppProjectsProjectIdInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppAdminUsersUserIdAssignRoute =
  AppAdminUsersUserIdAssignRouteImport.update({
    id: '/$userId/assign',
    path: '/$userId/assign',
    getParentRoute: () => AppAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/approvals': typeof AppApprovalsRouteWithChildren
  '/audit': typeof AppAuditRouteWithChildren
  '/deals': typeof AppDealsRouteWithChildren
  '/expenses': typeof AppExpensesRouteWithChildren
  '/homepage': typeof AppHomepageRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/timesheet': typeof AppTimesheetRouteWithChildren
  '/admin/groups': typeof AppAdminGroupsRouteWithChildren
  '/admin/roles': typeof AppAdminRolesRouteWithChildren
  '/admin/users': typeof AppAdminUsersRouteWithChildren
  '/approvals/timesheets': typeof AppApprovalsTimesheetsRoute
  '/audit/$traceId': typeof AppAuditTraceIdRouteWithChildren
  '/deals/$dealId': typeof AppDealsDealIdRouteWithChildren
  '/deals/new': typeof AppDealsNewRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AppAdminIndexRoute
  '/audit/': typeof AppAuditIndexRoute
  '/deals/': typeof AppDealsIndexRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/timesheet/': typeof AppTimesheetIndexRoute
  '/admin/groups/$groupId': typeof AppAdminGroupsGroupIdRoute
  '/admin/roles/$roleId': typeof AppAdminRolesRoleIdRoute
  '/audit/$traceId/visualizer': typeof AppAuditTraceIdVisualizerRoute
  '/deals/$dealId/estimate': typeof AppDealsDealIdEstimateRoute
  '/deals/$dealId/negotiate': typeof AppDealsDealIdNegotiateRoute
  '/deals/$dealId/proposal': typeof AppDealsDealIdProposalRoute
  '/deals/$dealId/qualify': typeof AppDealsDealIdQualifyRoute
  '/deals/$dealId/send-proposal': typeof AppDealsDealIdSendProposalRoute
  '/deals/$dealId/sign': typeof AppDealsDealIdSignRoute
  '/admin/groups/': typeof AppAdminGroupsIndexRoute
  '/admin/roles/': typeof AppAdminRolesIndexRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/audit/$traceId/': typeof AppAuditTraceIdIndexRoute
  '/admin/users/$userId/assign': typeof AppAdminUsersUserIdAssignRoute
  '/projects/$projectId/invoices/new': typeof AppProjectsProjectIdInvoicesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/approvals': typeof AppApprovalsRouteWithChildren
  '/homepage': typeof AppHomepageRoute
  '/approvals/timesheets': typeof AppApprovalsTimesheetsRoute
  '/deals/$dealId': typeof AppDealsDealIdRouteWithChildren
  '/deals/new': typeof AppDealsNewRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AppAdminIndexRoute
  '/audit': typeof AppAuditIndexRoute
  '/deals': typeof AppDealsIndexRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/timesheet': typeof AppTimesheetIndexRoute
  '/admin/groups/$groupId': typeof AppAdminGroupsGroupIdRoute
  '/admin/roles/$roleId': typeof AppAdminRolesRoleIdRoute
  '/audit/$traceId/visualizer': typeof AppAuditTraceIdVisualizerRoute
  '/deals/$dealId/estimate': typeof AppDealsDealIdEstimateRoute
  '/deals/$dealId/negotiate': typeof AppDealsDealIdNegotiateRoute
  '/deals/$dealId/proposal': typeof AppDealsDealIdProposalRoute
  '/deals/$dealId/qualify': typeof AppDealsDealIdQualifyRoute
  '/deals/$dealId/send-proposal': typeof AppDealsDealIdSendProposalRoute
  '/deals/$dealId/sign': typeof AppDealsDealIdSignRoute
  '/admin/groups': typeof AppAdminGroupsIndexRoute
  '/admin/roles': typeof AppAdminRolesIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/audit/$traceId': typeof AppAuditTraceIdIndexRoute
  '/admin/users/$userId/assign': typeof AppAdminUsersUserIdAssignRoute
  '/projects/$projectId/invoices/new': typeof AppProjectsProjectIdInvoicesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/approvals': typeof AppApprovalsRouteWithChildren
  '/_app/audit': typeof AppAuditRouteWithChildren
  '/_app/deals': typeof AppDealsRouteWithChildren
  '/_app/expenses': typeof AppExpensesRouteWithChildren
  '/_app/homepage': typeof AppHomepageRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/timesheet': typeof AppTimesheetRouteWithChildren
  '/_app/admin/groups': typeof AppAdminGroupsRouteWithChildren
  '/_app/admin/roles': typeof AppAdminRolesRouteWithChildren
  '/_app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/_app/approvals/timesheets': typeof AppApprovalsTimesheetsRoute
  '/_app/audit/$traceId': typeof AppAuditTraceIdRouteWithChildren
  '/_app/deals/$dealId': typeof AppDealsDealIdRouteWithChildren
  '/_app/deals/new': typeof AppDealsNewRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/audit/': typeof AppAuditIndexRoute
  '/_app/deals/': typeof AppDealsIndexRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/timesheet/': typeof AppTimesheetIndexRoute
  '/_app/admin/groups/$groupId': typeof AppAdminGroupsGroupIdRoute
  '/_app/admin/roles/$roleId': typeof AppAdminRolesRoleIdRoute
  '/_app/audit/$traceId/visualizer': typeof AppAuditTraceIdVisualizerRoute
  '/_app/deals/$dealId/estimate': typeof AppDealsDealIdEstimateRoute
  '/_app/deals/$dealId/negotiate': typeof AppDealsDealIdNegotiateRoute
  '/_app/deals/$dealId/proposal': typeof AppDealsDealIdProposalRoute
  '/_app/deals/$dealId/qualify': typeof AppDealsDealIdQualifyRoute
  '/_app/deals/$dealId/send-proposal': typeof AppDealsDealIdSendProposalRoute
  '/_app/deals/$dealId/sign': typeof AppDealsDealIdSignRoute
  '/_app/admin/groups/': typeof AppAdminGroupsIndexRoute
  '/_app/admin/roles/': typeof AppAdminRolesIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/audit/$traceId/': typeof AppAuditTraceIdIndexRoute
  '/_app/admin/users/$userId/assign': typeof AppAdminUsersUserIdAssignRoute
  '/_app/projects/$projectId/invoices/new': typeof AppProjectsProjectIdInvoicesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/approvals'
    | '/audit'
    | '/deals'
    | '/expenses'
    | '/homepage'
    | '/projects'
    | '/timesheet'
    | '/admin/groups'
    | '/admin/roles'
    | '/admin/users'
    | '/approvals/timesheets'
    | '/audit/$traceId'
    | '/deals/$dealId'
    | '/deals/new'
    | '/projects/$projectId'
    | '/api/auth/$'
    | '/admin/'
    | '/audit/'
    | '/deals/'
    | '/expenses/'
    | '/projects/'
    | '/timesheet/'
    | '/admin/groups/$groupId'
    | '/admin/roles/$roleId'
    | '/audit/$traceId/visualizer'
    | '/deals/$dealId/estimate'
    | '/deals/$dealId/negotiate'
    | '/deals/$dealId/proposal'
    | '/deals/$dealId/qualify'
    | '/deals/$dealId/send-proposal'
    | '/deals/$dealId/sign'
    | '/admin/groups/'
    | '/admin/roles/'
    | '/admin/users/'
    | '/audit/$traceId/'
    | '/admin/users/$userId/assign'
    | '/projects/$projectId/invoices/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/approvals'
    | '/homepage'
    | '/approvals/timesheets'
    | '/deals/$dealId'
    | '/deals/new'
    | '/projects/$projectId'
    | '/api/auth/$'
    | '/admin'
    | '/audit'
    | '/deals'
    | '/expenses'
    | '/projects'
    | '/timesheet'
    | '/admin/groups/$groupId'
    | '/admin/roles/$roleId'
    | '/audit/$traceId/visualizer'
    | '/deals/$dealId/estimate'
    | '/deals/$dealId/negotiate'
    | '/deals/$dealId/proposal'
    | '/deals/$dealId/qualify'
    | '/deals/$dealId/send-proposal'
    | '/deals/$dealId/sign'
    | '/admin/groups'
    | '/admin/roles'
    | '/admin/users'
    | '/audit/$traceId'
    | '/admin/users/$userId/assign'
    | '/projects/$projectId/invoices/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/approvals'
    | '/_app/audit'
    | '/_app/deals'
    | '/_app/expenses'
    | '/_app/homepage'
    | '/_app/projects'
    | '/_app/timesheet'
    | '/_app/admin/groups'
    | '/_app/admin/roles'
    | '/_app/admin/users'
    | '/_app/approvals/timesheets'
    | '/_app/audit/$traceId'
    | '/_app/deals/$dealId'
    | '/_app/deals/new'
    | '/_app/projects/$projectId'
    | '/api/auth/$'
    | '/_app/admin/'
    | '/_app/audit/'
    | '/_app/deals/'
    | '/_app/expenses/'
    | '/_app/projects/'
    | '/_app/timesheet/'
    | '/_app/admin/groups/$groupId'
    | '/_app/admin/roles/$roleId'
    | '/_app/audit/$traceId/visualizer'
    | '/_app/deals/$dealId/estimate'
    | '/_app/deals/$dealId/negotiate'
    | '/_app/deals/$dealId/proposal'
    | '/_app/deals/$dealId/qualify'
    | '/_app/deals/$dealId/send-proposal'
    | '/_app/deals/$dealId/sign'
    | '/_app/admin/groups/'
    | '/_app/admin/roles/'
    | '/_app/admin/users/'
    | '/_app/audit/$traceId/'
    | '/_app/admin/users/$userId/assign'
    | '/_app/projects/$projectId/invoices/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/timesheet': {
      id: '/_app/timesheet'
      path: '/timesheet'
      fullPath: '/timesheet'
      preLoaderRoute: typeof AppTimesheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/homepage': {
      id: '/_app/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof AppHomepageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals': {
      id: '/_app/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AppDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timesheet/': {
      id: '/_app/timesheet/'
      path: '/'
      fullPath: '/timesheet/'
      preLoaderRoute: typeof AppTimesheetIndexRouteImport
      parentRoute: typeof AppTimesheetRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppExpensesRoute
    }
    '/_app/deals/': {
      id: '/_app/deals/'
      path: '/'
      fullPath: '/deals/'
      preLoaderRoute: typeof AppDealsIndexRouteImport
      parentRoute: typeof AppDealsRoute
    }
    '/_app/audit/': {
      id: '/_app/audit/'
      path: '/'
      fullPath: '/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/deals/new': {
      id: '/_app/deals/new'
      path: '/new'
      fullPath: '/deals/new'
      preLoaderRoute: typeof AppDealsNewRouteImport
      parentRoute: typeof AppDealsRoute
    }
    '/_app/deals/$dealId': {
      id: '/_app/deals/$dealId'
      path: '/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof AppDealsDealIdRouteImport
      parentRoute: typeof AppDealsRoute
    }
    '/_app/audit/$traceId': {
      id: '/_app/audit/$traceId'
      path: '/$traceId'
      fullPath: '/audit/$traceId'
      preLoaderRoute: typeof AppAuditTraceIdRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/approvals/timesheets': {
      id: '/_app/approvals/timesheets'
      path: '/timesheets'
      fullPath: '/approvals/timesheets'
      preLoaderRoute: typeof AppApprovalsTimesheetsRouteImport
      parentRoute: typeof AppApprovalsRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/groups': {
      id: '/_app/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AppAdminGroupsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/audit/$traceId/': {
      id: '/_app/audit/$traceId/'
      path: '/'
      fullPath: '/audit/$traceId/'
      preLoaderRoute: typeof AppAuditTraceIdIndexRouteImport
      parentRoute: typeof AppAuditTraceIdRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/_app/admin/roles/': {
      id: '/_app/admin/roles/'
      path: '/'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AppAdminRolesIndexRouteImport
      parentRoute: typeof AppAdminRolesRoute
    }
    '/_app/admin/groups/': {
      id: '/_app/admin/groups/'
      path: '/'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AppAdminGroupsIndexRouteImport
      parentRoute: typeof AppAdminGroupsRoute
    }
    '/_app/deals/$dealId/sign': {
      id: '/_app/deals/$dealId/sign'
      path: '/sign'
      fullPath: '/deals/$dealId/sign'
      preLoaderRoute: typeof AppDealsDealIdSignRouteImport
      parentRoute: typeof AppDealsDealIdRoute
    }
    '/_app/deals/$dealId/send-proposal': {
      id: '/_app/deals/$dealId/send-proposal'
      path: '/send-proposal'
      fullPath: '/deals/$dealId/send-proposal'
      preLoaderRoute: typeof AppDealsDealIdSendProposalRouteImport
      parentRoute: typeof AppDealsDealIdRoute
    }
    '/_app/deals/$dealId/qualify': {
      id: '/_app/deals/$dealId/qualify'
      path: '/qualify'
      fullPath: '/deals/$dealId/qualify'
      preLoaderRoute: typeof AppDealsDealIdQualifyRouteImport
      parentRoute: typeof AppDealsDealIdRoute
    }
    '/_app/deals/$dealId/proposal': {
      id: '/_app/deals/$dealId/proposal'
      path: '/proposal'
      fullPath: '/deals/$dealId/proposal'
      preLoaderRoute: typeof AppDealsDealIdProposalRouteImport
      parentRoute: typeof AppDealsDealIdRoute
    }
    '/_app/deals/$dealId/negotiate': {
      id: '/_app/deals/$dealId/negotiate'
      path: '/negotiate'
      fullPath: '/deals/$dealId/negotiate'
      preLoaderRoute: typeof AppDealsDealIdNegotiateRouteImport
      parentRoute: typeof AppDealsDealIdRoute
    }
    '/_app/deals/$dealId/estimate': {
      id: '/_app/deals/$dealId/estimate'
      path: '/estimate'
      fullPath: '/deals/$dealId/estimate'
      preLoaderRoute: typeof AppDealsDealIdEstimateRouteImport
      parentRoute: typeof AppDealsDealIdRoute
    }
    '/_app/audit/$traceId/visualizer': {
      id: '/_app/audit/$traceId/visualizer'
      path: '/visualizer'
      fullPath: '/audit/$traceId/visualizer'
      preLoaderRoute: typeof AppAuditTraceIdVisualizerRouteImport
      parentRoute: typeof AppAuditTraceIdRoute
    }
    '/_app/admin/roles/$roleId': {
      id: '/_app/admin/roles/$roleId'
      path: '/$roleId'
      fullPath: '/admin/roles/$roleId'
      preLoaderRoute: typeof AppAdminRolesRoleIdRouteImport
      parentRoute: typeof AppAdminRolesRoute
    }
    '/_app/admin/groups/$groupId': {
      id: '/_app/admin/groups/$groupId'
      path: '/$groupId'
      fullPath: '/admin/groups/$groupId'
      preLoaderRoute: typeof AppAdminGroupsGroupIdRouteImport
      parentRoute: typeof AppAdminGroupsRoute
    }
    '/_app/projects/$projectId/invoices/new': {
      id: '/_app/projects/$projectId/invoices/new'
      path: '/invoices/new'
      fullPath: '/projects/$projectId/invoices/new'
      preLoaderRoute: typeof AppProjectsProjectIdInvoicesNewRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/admin/users/$userId/assign': {
      id: '/_app/admin/users/$userId/assign'
      path: '/$userId/assign'
      fullPath: '/admin/users/$userId/assign'
      preLoaderRoute: typeof AppAdminUsersUserIdAssignRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
  }
}

interface AppAdminGroupsRouteChildren {
  AppAdminGroupsGroupIdRoute: typeof AppAdminGroupsGroupIdRoute
  AppAdminGroupsIndexRoute: typeof AppAdminGroupsIndexRoute
}

const AppAdminGroupsRouteChildren: AppAdminGroupsRouteChildren = {
  AppAdminGroupsGroupIdRoute: AppAdminGroupsGroupIdRoute,
  AppAdminGroupsIndexRoute: AppAdminGroupsIndexRoute,
}

const AppAdminGroupsRouteWithChildren = AppAdminGroupsRoute._addFileChildren(
  AppAdminGroupsRouteChildren,
)

interface AppAdminRolesRouteChildren {
  AppAdminRolesRoleIdRoute: typeof AppAdminRolesRoleIdRoute
  AppAdminRolesIndexRoute: typeof AppAdminRolesIndexRoute
}

const AppAdminRolesRouteChildren: AppAdminRolesRouteChildren = {
  AppAdminRolesRoleIdRoute: AppAdminRolesRoleIdRoute,
  AppAdminRolesIndexRoute: AppAdminRolesIndexRoute,
}

const AppAdminRolesRouteWithChildren = AppAdminRolesRoute._addFileChildren(
  AppAdminRolesRouteChildren,
)

interface AppAdminUsersRouteChildren {
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
  AppAdminUsersUserIdAssignRoute: typeof AppAdminUsersUserIdAssignRoute
}

const AppAdminUsersRouteChildren: AppAdminUsersRouteChildren = {
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
  AppAdminUsersUserIdAssignRoute: AppAdminUsersUserIdAssignRoute,
}

const AppAdminUsersRouteWithChildren = AppAdminUsersRoute._addFileChildren(
  AppAdminUsersRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminGroupsRoute: typeof AppAdminGroupsRouteWithChildren
  AppAdminRolesRoute: typeof AppAdminRolesRouteWithChildren
  AppAdminUsersRoute: typeof AppAdminUsersRouteWithChildren
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminGroupsRoute: AppAdminGroupsRouteWithChildren,
  AppAdminRolesRoute: AppAdminRolesRouteWithChildren,
  AppAdminUsersRoute: AppAdminUsersRouteWithChildren,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppApprovalsRouteChildren {
  AppApprovalsTimesheetsRoute: typeof AppApprovalsTimesheetsRoute
}

const AppApprovalsRouteChildren: AppApprovalsRouteChildren = {
  AppApprovalsTimesheetsRoute: AppApprovalsTimesheetsRoute,
}

const AppApprovalsRouteWithChildren = AppApprovalsRoute._addFileChildren(
  AppApprovalsRouteChildren,
)

interface AppAuditTraceIdRouteChildren {
  AppAuditTraceIdVisualizerRoute: typeof AppAuditTraceIdVisualizerRoute
  AppAuditTraceIdIndexRoute: typeof AppAuditTraceIdIndexRoute
}

const AppAuditTraceIdRouteChildren: AppAuditTraceIdRouteChildren = {
  AppAuditTraceIdVisualizerRoute: AppAuditTraceIdVisualizerRoute,
  AppAuditTraceIdIndexRoute: AppAuditTraceIdIndexRoute,
}

const AppAuditTraceIdRouteWithChildren = AppAuditTraceIdRoute._addFileChildren(
  AppAuditTraceIdRouteChildren,
)

interface AppAuditRouteChildren {
  AppAuditTraceIdRoute: typeof AppAuditTraceIdRouteWithChildren
  AppAuditIndexRoute: typeof AppAuditIndexRoute
}

const AppAuditRouteChildren: AppAuditRouteChildren = {
  AppAuditTraceIdRoute: AppAuditTraceIdRouteWithChildren,
  AppAuditIndexRoute: AppAuditIndexRoute,
}

const AppAuditRouteWithChildren = AppAuditRoute._addFileChildren(
  AppAuditRouteChildren,
)

interface AppDealsDealIdRouteChildren {
  AppDealsDealIdEstimateRoute: typeof AppDealsDealIdEstimateRoute
  AppDealsDealIdNegotiateRoute: typeof AppDealsDealIdNegotiateRoute
  AppDealsDealIdProposalRoute: typeof AppDealsDealIdProposalRoute
  AppDealsDealIdQualifyRoute: typeof AppDealsDealIdQualifyRoute
  AppDealsDealIdSendProposalRoute: typeof AppDealsDealIdSendProposalRoute
  AppDealsDealIdSignRoute: typeof AppDealsDealIdSignRoute
}

const AppDealsDealIdRouteChildren: AppDealsDealIdRouteChildren = {
  AppDealsDealIdEstimateRoute: AppDealsDealIdEstimateRoute,
  AppDealsDealIdNegotiateRoute: AppDealsDealIdNegotiateRoute,
  AppDealsDealIdProposalRoute: AppDealsDealIdProposalRoute,
  AppDealsDealIdQualifyRoute: AppDealsDealIdQualifyRoute,
  AppDealsDealIdSendProposalRoute: AppDealsDealIdSendProposalRoute,
  AppDealsDealIdSignRoute: AppDealsDealIdSignRoute,
}

const AppDealsDealIdRouteWithChildren = AppDealsDealIdRoute._addFileChildren(
  AppDealsDealIdRouteChildren,
)

interface AppDealsRouteChildren {
  AppDealsDealIdRoute: typeof AppDealsDealIdRouteWithChildren
  AppDealsNewRoute: typeof AppDealsNewRoute
  AppDealsIndexRoute: typeof AppDealsIndexRoute
}

const AppDealsRouteChildren: AppDealsRouteChildren = {
  AppDealsDealIdRoute: AppDealsDealIdRouteWithChildren,
  AppDealsNewRoute: AppDealsNewRoute,
  AppDealsIndexRoute: AppDealsIndexRoute,
}

const AppDealsRouteWithChildren = AppDealsRoute._addFileChildren(
  AppDealsRouteChildren,
)

interface AppExpensesRouteChildren {
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
}

const AppExpensesRouteChildren: AppExpensesRouteChildren = {
  AppExpensesIndexRoute: AppExpensesIndexRoute,
}

const AppExpensesRouteWithChildren = AppExpensesRoute._addFileChildren(
  AppExpensesRouteChildren,
)

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdInvoicesNewRoute: typeof AppProjectsProjectIdInvoicesNewRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdInvoicesNewRoute: AppProjectsProjectIdInvoicesNewRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppTimesheetRouteChildren {
  AppTimesheetIndexRoute: typeof AppTimesheetIndexRoute
}

const AppTimesheetRouteChildren: AppTimesheetRouteChildren = {
  AppTimesheetIndexRoute: AppTimesheetIndexRoute,
}

const AppTimesheetRouteWithChildren = AppTimesheetRoute._addFileChildren(
  AppTimesheetRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppApprovalsRoute: typeof AppApprovalsRouteWithChildren
  AppAuditRoute: typeof AppAuditRouteWithChildren
  AppDealsRoute: typeof AppDealsRouteWithChildren
  AppExpensesRoute: typeof AppExpensesRouteWithChildren
  AppHomepageRoute: typeof AppHomepageRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppTimesheetRoute: typeof AppTimesheetRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppApprovalsRoute: AppApprovalsRouteWithChildren,
  AppAuditRoute: AppAuditRouteWithChildren,
  AppDealsRoute: AppDealsRouteWithChildren,
  AppExpensesRoute: AppExpensesRouteWithChildren,
  AppHomepageRoute: AppHomepageRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppTimesheetRoute: AppTimesheetRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
