/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSimpleRouteImport } from './routes/_app/simple'
import { Route as AppHomepageRouteImport } from './routes/_app/homepage'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppSimpleIndexRouteImport } from './routes/_app/simple/index'
import { Route as AppAuditIndexRouteImport } from './routes/_app/audit/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSimpleQueueRouteImport } from './routes/_app/simple/queue'
import { Route as AppSimpleNewRouteImport } from './routes/_app/simple/new'
import { Route as AppAuditTraceIdRouteImport } from './routes/_app/audit/$traceId'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminRolesRouteImport } from './routes/_app/admin/roles'
import { Route as AppAdminGroupsRouteImport } from './routes/_app/admin/groups'
import { Route as AppAuditTraceIdIndexRouteImport } from './routes/_app/audit/$traceId.index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users.index'
import { Route as AppAdminRolesIndexRouteImport } from './routes/_app/admin/roles.index'
import { Route as AppAdminGroupsIndexRouteImport } from './routes/_app/admin/groups.index'
import { Route as AppAuditTraceIdVisualizerRouteImport } from './routes/_app/audit/$traceId.visualizer'
import { Route as AppAdminRolesRoleIdRouteImport } from './routes/_app/admin/roles.$roleId'
import { Route as AppAdminGroupsGroupIdRouteImport } from './routes/_app/admin/groups.$groupId'
import { Route as AppSimpleTasksStoreWorkItemIdRouteImport } from './routes/_app/simple/tasks/store.$workItemId'
import { Route as AppAdminUsersUserIdAssignRouteImport } from './routes/_app/admin/users.$userId.assign'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimpleRoute = AppSimpleRouteImport.update({
  id: '/simple',
  path: '/simple',
  getParentRoute: () => AppRoute,
} as any)
const AppHomepageRoute = AppHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSimpleIndexRoute = AppSimpleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSimpleRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimpleQueueRoute = AppSimpleQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppSimpleRoute,
} as any)
const AppSimpleNewRoute = AppSimpleNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSimpleRoute,
} as any)
const AppAuditTraceIdRoute = AppAuditTraceIdRouteImport.update({
  id: '/$traceId',
  path: '/$traceId',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminGroupsRoute = AppAdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAuditTraceIdIndexRoute = AppAuditTraceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuditTraceIdRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminUsersRoute,
} as any)
const AppAdminRolesIndexRoute = AppAdminRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRolesRoute,
} as any)
const AppAdminGroupsIndexRoute = AppAdminGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminGroupsRoute,
} as any)
const AppAuditTraceIdVisualizerRoute =
  AppAuditTraceIdVisualizerRouteImport.update({
    id: '/visualizer',
    path: '/visualizer',
    getParentRoute: () => AppAuditTraceIdRoute,
  } as any)
const AppAdminRolesRoleIdRoute = AppAdminRolesRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => AppAdminRolesRoute,
} as any)
const AppAdminGroupsGroupIdRoute = AppAdminGroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => AppAdminGroupsRoute,
} as any)
const AppSimpleTasksStoreWorkItemIdRoute =
  AppSimpleTasksStoreWorkItemIdRouteImport.update({
    id: '/tasks/store/$workItemId',
    path: '/tasks/store/$workItemId',
    getParentRoute: () => AppSimpleRoute,
  } as any)
const AppAdminUsersUserIdAssignRoute =
  AppAdminUsersUserIdAssignRouteImport.update({
    id: '/$userId/assign',
    path: '/$userId/assign',
    getParentRoute: () => AppAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/audit': typeof AppAuditRouteWithChildren
  '/homepage': typeof AppHomepageRoute
  '/simple': typeof AppSimpleRouteWithChildren
  '/admin/groups': typeof AppAdminGroupsRouteWithChildren
  '/admin/roles': typeof AppAdminRolesRouteWithChildren
  '/admin/users': typeof AppAdminUsersRouteWithChildren
  '/audit/$traceId': typeof AppAuditTraceIdRouteWithChildren
  '/simple/new': typeof AppSimpleNewRoute
  '/simple/queue': typeof AppSimpleQueueRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AppAdminIndexRoute
  '/audit/': typeof AppAuditIndexRoute
  '/simple/': typeof AppSimpleIndexRoute
  '/admin/groups/$groupId': typeof AppAdminGroupsGroupIdRoute
  '/admin/roles/$roleId': typeof AppAdminRolesRoleIdRoute
  '/audit/$traceId/visualizer': typeof AppAuditTraceIdVisualizerRoute
  '/admin/groups/': typeof AppAdminGroupsIndexRoute
  '/admin/roles/': typeof AppAdminRolesIndexRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/audit/$traceId/': typeof AppAuditTraceIdIndexRoute
  '/admin/users/$userId/assign': typeof AppAdminUsersUserIdAssignRoute
  '/simple/tasks/store/$workItemId': typeof AppSimpleTasksStoreWorkItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/homepage': typeof AppHomepageRoute
  '/simple/new': typeof AppSimpleNewRoute
  '/simple/queue': typeof AppSimpleQueueRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AppAdminIndexRoute
  '/audit': typeof AppAuditIndexRoute
  '/simple': typeof AppSimpleIndexRoute
  '/admin/groups/$groupId': typeof AppAdminGroupsGroupIdRoute
  '/admin/roles/$roleId': typeof AppAdminRolesRoleIdRoute
  '/audit/$traceId/visualizer': typeof AppAuditTraceIdVisualizerRoute
  '/admin/groups': typeof AppAdminGroupsIndexRoute
  '/admin/roles': typeof AppAdminRolesIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/audit/$traceId': typeof AppAuditTraceIdIndexRoute
  '/admin/users/$userId/assign': typeof AppAdminUsersUserIdAssignRoute
  '/simple/tasks/store/$workItemId': typeof AppSimpleTasksStoreWorkItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/audit': typeof AppAuditRouteWithChildren
  '/_app/homepage': typeof AppHomepageRoute
  '/_app/simple': typeof AppSimpleRouteWithChildren
  '/_app/admin/groups': typeof AppAdminGroupsRouteWithChildren
  '/_app/admin/roles': typeof AppAdminRolesRouteWithChildren
  '/_app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/_app/audit/$traceId': typeof AppAuditTraceIdRouteWithChildren
  '/_app/simple/new': typeof AppSimpleNewRoute
  '/_app/simple/queue': typeof AppSimpleQueueRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/audit/': typeof AppAuditIndexRoute
  '/_app/simple/': typeof AppSimpleIndexRoute
  '/_app/admin/groups/$groupId': typeof AppAdminGroupsGroupIdRoute
  '/_app/admin/roles/$roleId': typeof AppAdminRolesRoleIdRoute
  '/_app/audit/$traceId/visualizer': typeof AppAuditTraceIdVisualizerRoute
  '/_app/admin/groups/': typeof AppAdminGroupsIndexRoute
  '/_app/admin/roles/': typeof AppAdminRolesIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/audit/$traceId/': typeof AppAuditTraceIdIndexRoute
  '/_app/admin/users/$userId/assign': typeof AppAdminUsersUserIdAssignRoute
  '/_app/simple/tasks/store/$workItemId': typeof AppSimpleTasksStoreWorkItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/audit'
    | '/homepage'
    | '/simple'
    | '/admin/groups'
    | '/admin/roles'
    | '/admin/users'
    | '/audit/$traceId'
    | '/simple/new'
    | '/simple/queue'
    | '/api/auth/$'
    | '/admin/'
    | '/audit/'
    | '/simple/'
    | '/admin/groups/$groupId'
    | '/admin/roles/$roleId'
    | '/audit/$traceId/visualizer'
    | '/admin/groups/'
    | '/admin/roles/'
    | '/admin/users/'
    | '/audit/$traceId/'
    | '/admin/users/$userId/assign'
    | '/simple/tasks/store/$workItemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/homepage'
    | '/simple/new'
    | '/simple/queue'
    | '/api/auth/$'
    | '/admin'
    | '/audit'
    | '/simple'
    | '/admin/groups/$groupId'
    | '/admin/roles/$roleId'
    | '/audit/$traceId/visualizer'
    | '/admin/groups'
    | '/admin/roles'
    | '/admin/users'
    | '/audit/$traceId'
    | '/admin/users/$userId/assign'
    | '/simple/tasks/store/$workItemId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/audit'
    | '/_app/homepage'
    | '/_app/simple'
    | '/_app/admin/groups'
    | '/_app/admin/roles'
    | '/_app/admin/users'
    | '/_app/audit/$traceId'
    | '/_app/simple/new'
    | '/_app/simple/queue'
    | '/api/auth/$'
    | '/_app/admin/'
    | '/_app/audit/'
    | '/_app/simple/'
    | '/_app/admin/groups/$groupId'
    | '/_app/admin/roles/$roleId'
    | '/_app/audit/$traceId/visualizer'
    | '/_app/admin/groups/'
    | '/_app/admin/roles/'
    | '/_app/admin/users/'
    | '/_app/audit/$traceId/'
    | '/_app/admin/users/$userId/assign'
    | '/_app/simple/tasks/store/$workItemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/simple': {
      id: '/_app/simple'
      path: '/simple'
      fullPath: '/simple'
      preLoaderRoute: typeof AppSimpleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/homepage': {
      id: '/_app/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof AppHomepageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/simple/': {
      id: '/_app/simple/'
      path: '/'
      fullPath: '/simple/'
      preLoaderRoute: typeof AppSimpleIndexRouteImport
      parentRoute: typeof AppSimpleRoute
    }
    '/_app/audit/': {
      id: '/_app/audit/'
      path: '/'
      fullPath: '/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/simple/queue': {
      id: '/_app/simple/queue'
      path: '/queue'
      fullPath: '/simple/queue'
      preLoaderRoute: typeof AppSimpleQueueRouteImport
      parentRoute: typeof AppSimpleRoute
    }
    '/_app/simple/new': {
      id: '/_app/simple/new'
      path: '/new'
      fullPath: '/simple/new'
      preLoaderRoute: typeof AppSimpleNewRouteImport
      parentRoute: typeof AppSimpleRoute
    }
    '/_app/audit/$traceId': {
      id: '/_app/audit/$traceId'
      path: '/$traceId'
      fullPath: '/audit/$traceId'
      preLoaderRoute: typeof AppAuditTraceIdRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/groups': {
      id: '/_app/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AppAdminGroupsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/audit/$traceId/': {
      id: '/_app/audit/$traceId/'
      path: '/'
      fullPath: '/audit/$traceId/'
      preLoaderRoute: typeof AppAuditTraceIdIndexRouteImport
      parentRoute: typeof AppAuditTraceIdRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/_app/admin/roles/': {
      id: '/_app/admin/roles/'
      path: '/'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AppAdminRolesIndexRouteImport
      parentRoute: typeof AppAdminRolesRoute
    }
    '/_app/admin/groups/': {
      id: '/_app/admin/groups/'
      path: '/'
      fullPath: '/admin/groups/'
      preLoaderRoute: typeof AppAdminGroupsIndexRouteImport
      parentRoute: typeof AppAdminGroupsRoute
    }
    '/_app/audit/$traceId/visualizer': {
      id: '/_app/audit/$traceId/visualizer'
      path: '/visualizer'
      fullPath: '/audit/$traceId/visualizer'
      preLoaderRoute: typeof AppAuditTraceIdVisualizerRouteImport
      parentRoute: typeof AppAuditTraceIdRoute
    }
    '/_app/admin/roles/$roleId': {
      id: '/_app/admin/roles/$roleId'
      path: '/$roleId'
      fullPath: '/admin/roles/$roleId'
      preLoaderRoute: typeof AppAdminRolesRoleIdRouteImport
      parentRoute: typeof AppAdminRolesRoute
    }
    '/_app/admin/groups/$groupId': {
      id: '/_app/admin/groups/$groupId'
      path: '/$groupId'
      fullPath: '/admin/groups/$groupId'
      preLoaderRoute: typeof AppAdminGroupsGroupIdRouteImport
      parentRoute: typeof AppAdminGroupsRoute
    }
    '/_app/simple/tasks/store/$workItemId': {
      id: '/_app/simple/tasks/store/$workItemId'
      path: '/tasks/store/$workItemId'
      fullPath: '/simple/tasks/store/$workItemId'
      preLoaderRoute: typeof AppSimpleTasksStoreWorkItemIdRouteImport
      parentRoute: typeof AppSimpleRoute
    }
    '/_app/admin/users/$userId/assign': {
      id: '/_app/admin/users/$userId/assign'
      path: '/$userId/assign'
      fullPath: '/admin/users/$userId/assign'
      preLoaderRoute: typeof AppAdminUsersUserIdAssignRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
  }
}

interface AppAdminGroupsRouteChildren {
  AppAdminGroupsGroupIdRoute: typeof AppAdminGroupsGroupIdRoute
  AppAdminGroupsIndexRoute: typeof AppAdminGroupsIndexRoute
}

const AppAdminGroupsRouteChildren: AppAdminGroupsRouteChildren = {
  AppAdminGroupsGroupIdRoute: AppAdminGroupsGroupIdRoute,
  AppAdminGroupsIndexRoute: AppAdminGroupsIndexRoute,
}

const AppAdminGroupsRouteWithChildren = AppAdminGroupsRoute._addFileChildren(
  AppAdminGroupsRouteChildren,
)

interface AppAdminRolesRouteChildren {
  AppAdminRolesRoleIdRoute: typeof AppAdminRolesRoleIdRoute
  AppAdminRolesIndexRoute: typeof AppAdminRolesIndexRoute
}

const AppAdminRolesRouteChildren: AppAdminRolesRouteChildren = {
  AppAdminRolesRoleIdRoute: AppAdminRolesRoleIdRoute,
  AppAdminRolesIndexRoute: AppAdminRolesIndexRoute,
}

const AppAdminRolesRouteWithChildren = AppAdminRolesRoute._addFileChildren(
  AppAdminRolesRouteChildren,
)

interface AppAdminUsersRouteChildren {
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
  AppAdminUsersUserIdAssignRoute: typeof AppAdminUsersUserIdAssignRoute
}

const AppAdminUsersRouteChildren: AppAdminUsersRouteChildren = {
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
  AppAdminUsersUserIdAssignRoute: AppAdminUsersUserIdAssignRoute,
}

const AppAdminUsersRouteWithChildren = AppAdminUsersRoute._addFileChildren(
  AppAdminUsersRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminGroupsRoute: typeof AppAdminGroupsRouteWithChildren
  AppAdminRolesRoute: typeof AppAdminRolesRouteWithChildren
  AppAdminUsersRoute: typeof AppAdminUsersRouteWithChildren
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminGroupsRoute: AppAdminGroupsRouteWithChildren,
  AppAdminRolesRoute: AppAdminRolesRouteWithChildren,
  AppAdminUsersRoute: AppAdminUsersRouteWithChildren,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppAuditTraceIdRouteChildren {
  AppAuditTraceIdVisualizerRoute: typeof AppAuditTraceIdVisualizerRoute
  AppAuditTraceIdIndexRoute: typeof AppAuditTraceIdIndexRoute
}

const AppAuditTraceIdRouteChildren: AppAuditTraceIdRouteChildren = {
  AppAuditTraceIdVisualizerRoute: AppAuditTraceIdVisualizerRoute,
  AppAuditTraceIdIndexRoute: AppAuditTraceIdIndexRoute,
}

const AppAuditTraceIdRouteWithChildren = AppAuditTraceIdRoute._addFileChildren(
  AppAuditTraceIdRouteChildren,
)

interface AppAuditRouteChildren {
  AppAuditTraceIdRoute: typeof AppAuditTraceIdRouteWithChildren
  AppAuditIndexRoute: typeof AppAuditIndexRoute
}

const AppAuditRouteChildren: AppAuditRouteChildren = {
  AppAuditTraceIdRoute: AppAuditTraceIdRouteWithChildren,
  AppAuditIndexRoute: AppAuditIndexRoute,
}

const AppAuditRouteWithChildren = AppAuditRoute._addFileChildren(
  AppAuditRouteChildren,
)

interface AppSimpleRouteChildren {
  AppSimpleNewRoute: typeof AppSimpleNewRoute
  AppSimpleQueueRoute: typeof AppSimpleQueueRoute
  AppSimpleIndexRoute: typeof AppSimpleIndexRoute
  AppSimpleTasksStoreWorkItemIdRoute: typeof AppSimpleTasksStoreWorkItemIdRoute
}

const AppSimpleRouteChildren: AppSimpleRouteChildren = {
  AppSimpleNewRoute: AppSimpleNewRoute,
  AppSimpleQueueRoute: AppSimpleQueueRoute,
  AppSimpleIndexRoute: AppSimpleIndexRoute,
  AppSimpleTasksStoreWorkItemIdRoute: AppSimpleTasksStoreWorkItemIdRoute,
}

const AppSimpleRouteWithChildren = AppSimpleRoute._addFileChildren(
  AppSimpleRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAuditRoute: typeof AppAuditRouteWithChildren
  AppHomepageRoute: typeof AppHomepageRoute
  AppSimpleRoute: typeof AppSimpleRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAuditRoute: AppAuditRouteWithChildren,
  AppHomepageRoute: AppHomepageRoute,
  AppSimpleRoute: AppSimpleRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
