/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppErRouteImport } from './routes/_app/er'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppErIndexRouteImport } from './routes/_app/er/index'
import { Route as AppAuditIndexRouteImport } from './routes/_app/audit/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppErQueueRouteImport } from './routes/_app/er/queue'
import { Route as AppErNewRouteImport } from './routes/_app/er/new'
import { Route as AppErPatientIdRouteImport } from './routes/_app/er/$patientId'
import { Route as AppAuditTraceIdRouteImport } from './routes/_app/audit/$traceId'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminRolesRouteImport } from './routes/_app/admin/roles'
import { Route as AppAdminGroupsRouteImport } from './routes/_app/admin/groups'
import { Route as AppAuditTraceIdIndexRouteImport } from './routes/_app/audit/$traceId.index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users.index'
import { Route as AppAuditTraceIdVisualizerRouteImport } from './routes/_app/audit/$traceId.visualizer'
import { Route as AppErTasksXrayWorkItemIdRouteImport } from './routes/_app/er/tasks.xray.$workItemId'
import { Route as AppErTasksTriageWorkItemIdRouteImport } from './routes/_app/er/tasks.triage.$workItemId'
import { Route as AppErTasksSurgeryWorkItemIdRouteImport } from './routes/_app/er/tasks.surgery.$workItemId'
import { Route as AppErTasksReviewWorkItemIdRouteImport } from './routes/_app/er/tasks.review.$workItemId'
import { Route as AppErTasksMedicationWorkItemIdRouteImport } from './routes/_app/er/tasks.medication.$workItemId'
import { Route as AppErTasksDischargeWorkItemIdRouteImport } from './routes/_app/er/tasks.discharge.$workItemId'
import { Route as AppErTasksDailymedicationWorkItemIdRouteImport } from './routes/_app/er/tasks.dailymedication.$workItemId'
import { Route as AppErTasksDailycheckWorkItemIdRouteImport } from './routes/_app/er/tasks.dailycheck.$workItemId'
import { Route as AppErTasksConsultWorkItemIdRouteImport } from './routes/_app/er/tasks.consult.$workItemId'
import { Route as AppErTasksBloodWorkItemIdRouteImport } from './routes/_app/er/tasks.blood.$workItemId'
import { Route as AppErTasksAdmissionWorkItemIdRouteImport } from './routes/_app/er/tasks.admission.$workItemId'
import { Route as AppAdminUsersUserIdAssignRouteImport } from './routes/_app/admin/users.$userId.assign'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppErRoute = AppErRouteImport.update({
  id: '/er',
  path: '/er',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppErIndexRoute = AppErIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppErRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppErQueueRoute = AppErQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppErRoute,
} as any)
const AppErNewRoute = AppErNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppErRoute,
} as any)
const AppErPatientIdRoute = AppErPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => AppErRoute,
} as any)
const AppAuditTraceIdRoute = AppAuditTraceIdRouteImport.update({
  id: '/$traceId',
  path: '/$traceId',
  getParentRoute: () => AppAuditRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminGroupsRoute = AppAdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAuditTraceIdIndexRoute = AppAuditTraceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuditTraceIdRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminUsersRoute,
} as any)
const AppAuditTraceIdVisualizerRoute =
  AppAuditTraceIdVisualizerRouteImport.update({
    id: '/visualizer',
    path: '/visualizer',
    getParentRoute: () => AppAuditTraceIdRoute,
  } as any)
const AppErTasksXrayWorkItemIdRoute =
  AppErTasksXrayWorkItemIdRouteImport.update({
    id: '/tasks/xray/$workItemId',
    path: '/tasks/xray/$workItemId',
    getParentRoute: () => AppErRoute,
  } as any)
const AppErTasksTriageWorkItemIdRoute =
  AppErTasksTriageWorkItemIdRouteImport.update({
    id: '/tasks/triage/$workItemId',
    path: '/tasks/triage/$workItemId',
    getParentRoute: () => AppErRoute,
  } as any)
const AppErTasksSurgeryWorkItemIdRoute =
  AppErTasksSurgeryWorkItemIdRouteImport.update({
    id: '/tasks/surgery/$workItemId',
    path: '/tasks/surgery/$workItemId',
    getParentRoute: () => AppErRoute,
  } as any)
const AppErTasksReviewWorkItemIdRoute =
  AppErTasksReviewWorkItemIdRouteImport.update({
    id: '/tasks/review/$workItemId',
    path: '/tasks/review/$workItemId',
    getParentRoute: () => AppErRoute,
  } as any)
const AppErTasksMedicationWorkItemIdRoute =
  AppErTasksMedicationWorkItemIdRouteImport.update({
    id: '/tasks/medication/$workItemId',
    path: '/tasks/medication/$workItemId',
    getParentRoute: () => AppErRoute,
  } as any)
const AppErTasksDischargeWorkItemIdRoute =
  AppErTasksDischargeWorkItemIdRouteImport.update({
    id: '/tasks/discharge/$workItemId',
    path: '/tasks/discharge/$workItemId',
    getParentRoute: () => AppErRoute,
  } as any)
const AppErTasksDailymedicationWorkItemIdRoute =
  AppErTasksDailymedicationWorkItemIdRouteImport.update({
    id: '/tasks/dailymedication/$workItemId',
    path: '/tasks/dailymedication/$workItemId',
    getParentRoute: () => AppErRoute,
  } as any)
const AppErTasksDailycheckWorkItemIdRoute =
  AppErTasksDailycheckWorkItemIdRouteImport.update({
    id: '/tasks/dailycheck/$workItemId',
    path: '/tasks/dailycheck/$workItemId',
    getParentRoute: () => AppErRoute,
  } as any)
const AppErTasksConsultWorkItemIdRoute =
  AppErTasksConsultWorkItemIdRouteImport.update({
    id: '/tasks/consult/$workItemId',
    path: '/tasks/consult/$workItemId',
    getParentRoute: () => AppErRoute,
  } as any)
const AppErTasksBloodWorkItemIdRoute =
  AppErTasksBloodWorkItemIdRouteImport.update({
    id: '/tasks/blood/$workItemId',
    path: '/tasks/blood/$workItemId',
    getParentRoute: () => AppErRoute,
  } as any)
const AppErTasksAdmissionWorkItemIdRoute =
  AppErTasksAdmissionWorkItemIdRouteImport.update({
    id: '/tasks/admission/$workItemId',
    path: '/tasks/admission/$workItemId',
    getParentRoute: () => AppErRoute,
  } as any)
const AppAdminUsersUserIdAssignRoute =
  AppAdminUsersUserIdAssignRouteImport.update({
    id: '/$userId/assign',
    path: '/$userId/assign',
    getParentRoute: () => AppAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/audit': typeof AppAuditRouteWithChildren
  '/er': typeof AppErRouteWithChildren
  '/admin/groups': typeof AppAdminGroupsRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/admin/users': typeof AppAdminUsersRouteWithChildren
  '/audit/$traceId': typeof AppAuditTraceIdRouteWithChildren
  '/er/$patientId': typeof AppErPatientIdRoute
  '/er/new': typeof AppErNewRoute
  '/er/queue': typeof AppErQueueRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AppAdminIndexRoute
  '/audit/': typeof AppAuditIndexRoute
  '/er/': typeof AppErIndexRoute
  '/audit/$traceId/visualizer': typeof AppAuditTraceIdVisualizerRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/audit/$traceId/': typeof AppAuditTraceIdIndexRoute
  '/admin/users/$userId/assign': typeof AppAdminUsersUserIdAssignRoute
  '/er/tasks/admission/$workItemId': typeof AppErTasksAdmissionWorkItemIdRoute
  '/er/tasks/blood/$workItemId': typeof AppErTasksBloodWorkItemIdRoute
  '/er/tasks/consult/$workItemId': typeof AppErTasksConsultWorkItemIdRoute
  '/er/tasks/dailycheck/$workItemId': typeof AppErTasksDailycheckWorkItemIdRoute
  '/er/tasks/dailymedication/$workItemId': typeof AppErTasksDailymedicationWorkItemIdRoute
  '/er/tasks/discharge/$workItemId': typeof AppErTasksDischargeWorkItemIdRoute
  '/er/tasks/medication/$workItemId': typeof AppErTasksMedicationWorkItemIdRoute
  '/er/tasks/review/$workItemId': typeof AppErTasksReviewWorkItemIdRoute
  '/er/tasks/surgery/$workItemId': typeof AppErTasksSurgeryWorkItemIdRoute
  '/er/tasks/triage/$workItemId': typeof AppErTasksTriageWorkItemIdRoute
  '/er/tasks/xray/$workItemId': typeof AppErTasksXrayWorkItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/groups': typeof AppAdminGroupsRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/er/$patientId': typeof AppErPatientIdRoute
  '/er/new': typeof AppErNewRoute
  '/er/queue': typeof AppErQueueRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AppAdminIndexRoute
  '/audit': typeof AppAuditIndexRoute
  '/er': typeof AppErIndexRoute
  '/audit/$traceId/visualizer': typeof AppAuditTraceIdVisualizerRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/audit/$traceId': typeof AppAuditTraceIdIndexRoute
  '/admin/users/$userId/assign': typeof AppAdminUsersUserIdAssignRoute
  '/er/tasks/admission/$workItemId': typeof AppErTasksAdmissionWorkItemIdRoute
  '/er/tasks/blood/$workItemId': typeof AppErTasksBloodWorkItemIdRoute
  '/er/tasks/consult/$workItemId': typeof AppErTasksConsultWorkItemIdRoute
  '/er/tasks/dailycheck/$workItemId': typeof AppErTasksDailycheckWorkItemIdRoute
  '/er/tasks/dailymedication/$workItemId': typeof AppErTasksDailymedicationWorkItemIdRoute
  '/er/tasks/discharge/$workItemId': typeof AppErTasksDischargeWorkItemIdRoute
  '/er/tasks/medication/$workItemId': typeof AppErTasksMedicationWorkItemIdRoute
  '/er/tasks/review/$workItemId': typeof AppErTasksReviewWorkItemIdRoute
  '/er/tasks/surgery/$workItemId': typeof AppErTasksSurgeryWorkItemIdRoute
  '/er/tasks/triage/$workItemId': typeof AppErTasksTriageWorkItemIdRoute
  '/er/tasks/xray/$workItemId': typeof AppErTasksXrayWorkItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/audit': typeof AppAuditRouteWithChildren
  '/_app/er': typeof AppErRouteWithChildren
  '/_app/admin/groups': typeof AppAdminGroupsRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/_app/audit/$traceId': typeof AppAuditTraceIdRouteWithChildren
  '/_app/er/$patientId': typeof AppErPatientIdRoute
  '/_app/er/new': typeof AppErNewRoute
  '/_app/er/queue': typeof AppErQueueRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/audit/': typeof AppAuditIndexRoute
  '/_app/er/': typeof AppErIndexRoute
  '/_app/audit/$traceId/visualizer': typeof AppAuditTraceIdVisualizerRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/audit/$traceId/': typeof AppAuditTraceIdIndexRoute
  '/_app/admin/users/$userId/assign': typeof AppAdminUsersUserIdAssignRoute
  '/_app/er/tasks/admission/$workItemId': typeof AppErTasksAdmissionWorkItemIdRoute
  '/_app/er/tasks/blood/$workItemId': typeof AppErTasksBloodWorkItemIdRoute
  '/_app/er/tasks/consult/$workItemId': typeof AppErTasksConsultWorkItemIdRoute
  '/_app/er/tasks/dailycheck/$workItemId': typeof AppErTasksDailycheckWorkItemIdRoute
  '/_app/er/tasks/dailymedication/$workItemId': typeof AppErTasksDailymedicationWorkItemIdRoute
  '/_app/er/tasks/discharge/$workItemId': typeof AppErTasksDischargeWorkItemIdRoute
  '/_app/er/tasks/medication/$workItemId': typeof AppErTasksMedicationWorkItemIdRoute
  '/_app/er/tasks/review/$workItemId': typeof AppErTasksReviewWorkItemIdRoute
  '/_app/er/tasks/surgery/$workItemId': typeof AppErTasksSurgeryWorkItemIdRoute
  '/_app/er/tasks/triage/$workItemId': typeof AppErTasksTriageWorkItemIdRoute
  '/_app/er/tasks/xray/$workItemId': typeof AppErTasksXrayWorkItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/audit'
    | '/er'
    | '/admin/groups'
    | '/admin/roles'
    | '/admin/users'
    | '/audit/$traceId'
    | '/er/$patientId'
    | '/er/new'
    | '/er/queue'
    | '/api/auth/$'
    | '/admin/'
    | '/audit/'
    | '/er/'
    | '/audit/$traceId/visualizer'
    | '/admin/users/'
    | '/audit/$traceId/'
    | '/admin/users/$userId/assign'
    | '/er/tasks/admission/$workItemId'
    | '/er/tasks/blood/$workItemId'
    | '/er/tasks/consult/$workItemId'
    | '/er/tasks/dailycheck/$workItemId'
    | '/er/tasks/dailymedication/$workItemId'
    | '/er/tasks/discharge/$workItemId'
    | '/er/tasks/medication/$workItemId'
    | '/er/tasks/review/$workItemId'
    | '/er/tasks/surgery/$workItemId'
    | '/er/tasks/triage/$workItemId'
    | '/er/tasks/xray/$workItemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/groups'
    | '/admin/roles'
    | '/er/$patientId'
    | '/er/new'
    | '/er/queue'
    | '/api/auth/$'
    | '/admin'
    | '/audit'
    | '/er'
    | '/audit/$traceId/visualizer'
    | '/admin/users'
    | '/audit/$traceId'
    | '/admin/users/$userId/assign'
    | '/er/tasks/admission/$workItemId'
    | '/er/tasks/blood/$workItemId'
    | '/er/tasks/consult/$workItemId'
    | '/er/tasks/dailycheck/$workItemId'
    | '/er/tasks/dailymedication/$workItemId'
    | '/er/tasks/discharge/$workItemId'
    | '/er/tasks/medication/$workItemId'
    | '/er/tasks/review/$workItemId'
    | '/er/tasks/surgery/$workItemId'
    | '/er/tasks/triage/$workItemId'
    | '/er/tasks/xray/$workItemId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/audit'
    | '/_app/er'
    | '/_app/admin/groups'
    | '/_app/admin/roles'
    | '/_app/admin/users'
    | '/_app/audit/$traceId'
    | '/_app/er/$patientId'
    | '/_app/er/new'
    | '/_app/er/queue'
    | '/api/auth/$'
    | '/_app/admin/'
    | '/_app/audit/'
    | '/_app/er/'
    | '/_app/audit/$traceId/visualizer'
    | '/_app/admin/users/'
    | '/_app/audit/$traceId/'
    | '/_app/admin/users/$userId/assign'
    | '/_app/er/tasks/admission/$workItemId'
    | '/_app/er/tasks/blood/$workItemId'
    | '/_app/er/tasks/consult/$workItemId'
    | '/_app/er/tasks/dailycheck/$workItemId'
    | '/_app/er/tasks/dailymedication/$workItemId'
    | '/_app/er/tasks/discharge/$workItemId'
    | '/_app/er/tasks/medication/$workItemId'
    | '/_app/er/tasks/review/$workItemId'
    | '/_app/er/tasks/surgery/$workItemId'
    | '/_app/er/tasks/triage/$workItemId'
    | '/_app/er/tasks/xray/$workItemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/er': {
      id: '/_app/er'
      path: '/er'
      fullPath: '/er'
      preLoaderRoute: typeof AppErRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/er/': {
      id: '/_app/er/'
      path: '/'
      fullPath: '/er/'
      preLoaderRoute: typeof AppErIndexRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/audit/': {
      id: '/_app/audit/'
      path: '/'
      fullPath: '/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/er/queue': {
      id: '/_app/er/queue'
      path: '/queue'
      fullPath: '/er/queue'
      preLoaderRoute: typeof AppErQueueRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/er/new': {
      id: '/_app/er/new'
      path: '/new'
      fullPath: '/er/new'
      preLoaderRoute: typeof AppErNewRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/er/$patientId': {
      id: '/_app/er/$patientId'
      path: '/$patientId'
      fullPath: '/er/$patientId'
      preLoaderRoute: typeof AppErPatientIdRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/audit/$traceId': {
      id: '/_app/audit/$traceId'
      path: '/$traceId'
      fullPath: '/audit/$traceId'
      preLoaderRoute: typeof AppAuditTraceIdRouteImport
      parentRoute: typeof AppAuditRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/groups': {
      id: '/_app/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AppAdminGroupsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/audit/$traceId/': {
      id: '/_app/audit/$traceId/'
      path: '/'
      fullPath: '/audit/$traceId/'
      preLoaderRoute: typeof AppAuditTraceIdIndexRouteImport
      parentRoute: typeof AppAuditTraceIdRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/_app/audit/$traceId/visualizer': {
      id: '/_app/audit/$traceId/visualizer'
      path: '/visualizer'
      fullPath: '/audit/$traceId/visualizer'
      preLoaderRoute: typeof AppAuditTraceIdVisualizerRouteImport
      parentRoute: typeof AppAuditTraceIdRoute
    }
    '/_app/er/tasks/xray/$workItemId': {
      id: '/_app/er/tasks/xray/$workItemId'
      path: '/tasks/xray/$workItemId'
      fullPath: '/er/tasks/xray/$workItemId'
      preLoaderRoute: typeof AppErTasksXrayWorkItemIdRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/er/tasks/triage/$workItemId': {
      id: '/_app/er/tasks/triage/$workItemId'
      path: '/tasks/triage/$workItemId'
      fullPath: '/er/tasks/triage/$workItemId'
      preLoaderRoute: typeof AppErTasksTriageWorkItemIdRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/er/tasks/surgery/$workItemId': {
      id: '/_app/er/tasks/surgery/$workItemId'
      path: '/tasks/surgery/$workItemId'
      fullPath: '/er/tasks/surgery/$workItemId'
      preLoaderRoute: typeof AppErTasksSurgeryWorkItemIdRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/er/tasks/review/$workItemId': {
      id: '/_app/er/tasks/review/$workItemId'
      path: '/tasks/review/$workItemId'
      fullPath: '/er/tasks/review/$workItemId'
      preLoaderRoute: typeof AppErTasksReviewWorkItemIdRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/er/tasks/medication/$workItemId': {
      id: '/_app/er/tasks/medication/$workItemId'
      path: '/tasks/medication/$workItemId'
      fullPath: '/er/tasks/medication/$workItemId'
      preLoaderRoute: typeof AppErTasksMedicationWorkItemIdRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/er/tasks/discharge/$workItemId': {
      id: '/_app/er/tasks/discharge/$workItemId'
      path: '/tasks/discharge/$workItemId'
      fullPath: '/er/tasks/discharge/$workItemId'
      preLoaderRoute: typeof AppErTasksDischargeWorkItemIdRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/er/tasks/dailymedication/$workItemId': {
      id: '/_app/er/tasks/dailymedication/$workItemId'
      path: '/tasks/dailymedication/$workItemId'
      fullPath: '/er/tasks/dailymedication/$workItemId'
      preLoaderRoute: typeof AppErTasksDailymedicationWorkItemIdRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/er/tasks/dailycheck/$workItemId': {
      id: '/_app/er/tasks/dailycheck/$workItemId'
      path: '/tasks/dailycheck/$workItemId'
      fullPath: '/er/tasks/dailycheck/$workItemId'
      preLoaderRoute: typeof AppErTasksDailycheckWorkItemIdRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/er/tasks/consult/$workItemId': {
      id: '/_app/er/tasks/consult/$workItemId'
      path: '/tasks/consult/$workItemId'
      fullPath: '/er/tasks/consult/$workItemId'
      preLoaderRoute: typeof AppErTasksConsultWorkItemIdRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/er/tasks/blood/$workItemId': {
      id: '/_app/er/tasks/blood/$workItemId'
      path: '/tasks/blood/$workItemId'
      fullPath: '/er/tasks/blood/$workItemId'
      preLoaderRoute: typeof AppErTasksBloodWorkItemIdRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/er/tasks/admission/$workItemId': {
      id: '/_app/er/tasks/admission/$workItemId'
      path: '/tasks/admission/$workItemId'
      fullPath: '/er/tasks/admission/$workItemId'
      preLoaderRoute: typeof AppErTasksAdmissionWorkItemIdRouteImport
      parentRoute: typeof AppErRoute
    }
    '/_app/admin/users/$userId/assign': {
      id: '/_app/admin/users/$userId/assign'
      path: '/$userId/assign'
      fullPath: '/admin/users/$userId/assign'
      preLoaderRoute: typeof AppAdminUsersUserIdAssignRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
  }
}

interface AppAdminUsersRouteChildren {
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
  AppAdminUsersUserIdAssignRoute: typeof AppAdminUsersUserIdAssignRoute
}

const AppAdminUsersRouteChildren: AppAdminUsersRouteChildren = {
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
  AppAdminUsersUserIdAssignRoute: AppAdminUsersUserIdAssignRoute,
}

const AppAdminUsersRouteWithChildren = AppAdminUsersRoute._addFileChildren(
  AppAdminUsersRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminGroupsRoute: typeof AppAdminGroupsRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRouteWithChildren
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminGroupsRoute: AppAdminGroupsRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminUsersRoute: AppAdminUsersRouteWithChildren,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppAuditTraceIdRouteChildren {
  AppAuditTraceIdVisualizerRoute: typeof AppAuditTraceIdVisualizerRoute
  AppAuditTraceIdIndexRoute: typeof AppAuditTraceIdIndexRoute
}

const AppAuditTraceIdRouteChildren: AppAuditTraceIdRouteChildren = {
  AppAuditTraceIdVisualizerRoute: AppAuditTraceIdVisualizerRoute,
  AppAuditTraceIdIndexRoute: AppAuditTraceIdIndexRoute,
}

const AppAuditTraceIdRouteWithChildren = AppAuditTraceIdRoute._addFileChildren(
  AppAuditTraceIdRouteChildren,
)

interface AppAuditRouteChildren {
  AppAuditTraceIdRoute: typeof AppAuditTraceIdRouteWithChildren
  AppAuditIndexRoute: typeof AppAuditIndexRoute
}

const AppAuditRouteChildren: AppAuditRouteChildren = {
  AppAuditTraceIdRoute: AppAuditTraceIdRouteWithChildren,
  AppAuditIndexRoute: AppAuditIndexRoute,
}

const AppAuditRouteWithChildren = AppAuditRoute._addFileChildren(
  AppAuditRouteChildren,
)

interface AppErRouteChildren {
  AppErPatientIdRoute: typeof AppErPatientIdRoute
  AppErNewRoute: typeof AppErNewRoute
  AppErQueueRoute: typeof AppErQueueRoute
  AppErIndexRoute: typeof AppErIndexRoute
  AppErTasksAdmissionWorkItemIdRoute: typeof AppErTasksAdmissionWorkItemIdRoute
  AppErTasksBloodWorkItemIdRoute: typeof AppErTasksBloodWorkItemIdRoute
  AppErTasksConsultWorkItemIdRoute: typeof AppErTasksConsultWorkItemIdRoute
  AppErTasksDailycheckWorkItemIdRoute: typeof AppErTasksDailycheckWorkItemIdRoute
  AppErTasksDailymedicationWorkItemIdRoute: typeof AppErTasksDailymedicationWorkItemIdRoute
  AppErTasksDischargeWorkItemIdRoute: typeof AppErTasksDischargeWorkItemIdRoute
  AppErTasksMedicationWorkItemIdRoute: typeof AppErTasksMedicationWorkItemIdRoute
  AppErTasksReviewWorkItemIdRoute: typeof AppErTasksReviewWorkItemIdRoute
  AppErTasksSurgeryWorkItemIdRoute: typeof AppErTasksSurgeryWorkItemIdRoute
  AppErTasksTriageWorkItemIdRoute: typeof AppErTasksTriageWorkItemIdRoute
  AppErTasksXrayWorkItemIdRoute: typeof AppErTasksXrayWorkItemIdRoute
}

const AppErRouteChildren: AppErRouteChildren = {
  AppErPatientIdRoute: AppErPatientIdRoute,
  AppErNewRoute: AppErNewRoute,
  AppErQueueRoute: AppErQueueRoute,
  AppErIndexRoute: AppErIndexRoute,
  AppErTasksAdmissionWorkItemIdRoute: AppErTasksAdmissionWorkItemIdRoute,
  AppErTasksBloodWorkItemIdRoute: AppErTasksBloodWorkItemIdRoute,
  AppErTasksConsultWorkItemIdRoute: AppErTasksConsultWorkItemIdRoute,
  AppErTasksDailycheckWorkItemIdRoute: AppErTasksDailycheckWorkItemIdRoute,
  AppErTasksDailymedicationWorkItemIdRoute:
    AppErTasksDailymedicationWorkItemIdRoute,
  AppErTasksDischargeWorkItemIdRoute: AppErTasksDischargeWorkItemIdRoute,
  AppErTasksMedicationWorkItemIdRoute: AppErTasksMedicationWorkItemIdRoute,
  AppErTasksReviewWorkItemIdRoute: AppErTasksReviewWorkItemIdRoute,
  AppErTasksSurgeryWorkItemIdRoute: AppErTasksSurgeryWorkItemIdRoute,
  AppErTasksTriageWorkItemIdRoute: AppErTasksTriageWorkItemIdRoute,
  AppErTasksXrayWorkItemIdRoute: AppErTasksXrayWorkItemIdRoute,
}

const AppErRouteWithChildren = AppErRoute._addFileChildren(AppErRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAuditRoute: typeof AppAuditRouteWithChildren
  AppErRoute: typeof AppErRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAuditRoute: AppAuditRouteWithChildren,
  AppErRoute: AppErRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
